[github_app]
# these toggles allows running the github app from custom deployments
bot_user = "github-actions[bot]"
override_deployment_type = true
# in some deployments it's possible to get duplicate requests if the handling is long,
# these settings are used to avoid handling duplicate requests.
duplicate_requests_cache = false
duplicate_requests_cache_ttl = 60  # in seconds
# settings for "pull_request" event
handle_pr_actions = ['opened', 'reopened', 'ready_for_review', 'review_requested']
pr_commands = [
    "/describe --pr_description.add_original_user_description=true --pr_description.keep_original_user_title=true",
    "/review --pr_reviewer.num_code_suggestions=0",
    "/improve --pr_code_suggestions.summarize=true",
]
# settings for "pull_request" event with "synchronize" action - used to detect and handle push triggers for new commits
handle_push_trigger = false
push_trigger_ignore_bot_commits = true
push_trigger_ignore_merge_commits = true
push_trigger_wait_for_initial_review = true
push_trigger_pending_tasks_backlog = true
push_trigger_pending_tasks_ttl = 300
push_commands = [
    "/describe --pr_description.add_original_user_description=true --pr_description.keep_original_user_title=true",
    """/auto_review -i \
       --pr_reviewer.require_focused_review=false \
       --pr_reviewer.require_score_review=false \
       --pr_reviewer.require_tests_review=false \
       --pr_reviewer.require_security_review=false \
       --pr_reviewer.require_estimate_effort_to_review=false \
       --pr_reviewer.num_code_suggestions=0 \
       --pr_reviewer.inline_code_comments=false \
       --pr_reviewer.remove_previous_review_comment=true \
       --pr_reviewer.require_all_thresholds_for_incremental_review=false \
       --pr_reviewer.minimal_commits_for_incremental_review=5 \
       --pr_reviewer.minimal_minutes_for_incremental_review=30 \
       --pr_reviewer.extra_instructions='' \
    """
]
